import 'dotenv/config';
import { NestFactory } from '@nestjs/core';
import { DataSource } from 'typeorm';
import { AppModule } from './app.module';
import { Usuario, TipoUsuario } from './usuario/entities/usuario.entity';
import { Produto, medidaUnidade, tipoUnidade } from './produto/entities/produto.entity';
import { Receita, tipoDificuldade } from './receita/entities/receita.entity';
import { ReceitaIngrediente } from './receita/entities/receita-ingredientes.entity';

const baseDate = new Date('2026-06-27T12:00:00.000Z');

function addMinutes(minutes: number) {
  return new Date(baseDate.getTime() + minutes * 60_000);
}

async function seed() {
  const app = await NestFactory.createApplicationContext(AppModule, {
    logger: ['error', 'warn', 'log'],
  });
  const dataSource = app.get(DataSource);

  await dataSource.query(
    'TRUNCATE TABLE "receita_ingredientes", "receitas_concluidas", "receitas", "usuarios", "produtos" RESTART IDENTITY CASCADE',
  );

  const usuarioRepository = dataSource.getRepository(Usuario);
  const produtoRepository = dataSource.getRepository(Produto);
  const receitaRepository = dataSource.getRepository(Receita);
  const receitaIngredienteRepository =
    dataSource.getRepository(ReceitaIngrediente);

  const produtos = await produtoRepository.save(
    [
      {
        nome: 'Ovos caipiras',
        idCategoria: 1,
        descricao: 'Ovos frescos para receitas proteicas',
        marca: 'Fazenda Bom Dia',
        alergenos: ['ovo'],
        tipoUnidade: tipoUnidade.UNIDADE,
        medidaUnidade: medidaUnidade.UNIDADE,
        preco: 12.9,
        precoPromocional: 10.9,
        ativo: true,
        criadoEm: addMinutes(1),
      },
      {
        nome: 'Banana prata',
        idCategoria: 2,
        descricao: 'Banana madura para vitaminas e bowls',
        marca: 'Mercado Fresco',
        alergenos: [],
        tipoUnidade: tipoUnidade.PESO,
        medidaUnidade: medidaUnidade.KILO,
        preco: 6.49,
        ativo: true,
        criadoEm: addMinutes(2),
      },
      {
        nome: 'Tomate italiano',
        idCategoria: 3,
        descricao: 'Tomate para saladas e omeletes',
        marca: 'Horta Viva',
        alergenos: [],
        tipoUnidade: tipoUnidade.PESO,
        medidaUnidade: medidaUnidade.KILO,
        preco: 7.25,
        ativo: true,
        criadoEm: addMinutes(3),
      },
      {
        nome: 'Aveia em flocos',
        idCategoria: 4,
        descricao: 'Aveia para preparos saudáveis',
        marca: 'Vital Natural',
        alergenos: ['gluten'],
        tipoUnidade: tipoUnidade.PESO,
        medidaUnidade: medidaUnidade.PACOTE,
        preco: 9.9,
        ativo: true,
        criadoEm: addMinutes(4),
      },
      {
        nome: 'Leite integral',
        idCategoria: 5,
        descricao: 'Leite para vitaminas e receitas',
        marca: 'Boa Fazenda',
        alergenos: ['lactose'],
        tipoUnidade: tipoUnidade.VOLUME,
        medidaUnidade: medidaUnidade.LITRO,
        preco: 5.59,
        ativo: true,
        criadoEm: addMinutes(5),
      },
      {
        nome: 'Peito de frango',
        idCategoria: 6,
        descricao: 'Frango para bowls e pratos principais',
        marca: 'Proteico',
        alergenos: [],
        tipoUnidade: tipoUnidade.PESO,
        medidaUnidade: medidaUnidade.KILO,
        preco: 22.9,
        ativo: true,
        criadoEm: addMinutes(6),
      },
      {
        nome: 'Cebolinha',
        idCategoria: 7,
        descricao: 'Erva fresca para finalizar pratos',
        marca: 'Horta Viva',
        alergenos: [],
        tipoUnidade: tipoUnidade.UNIDADE,
        medidaUnidade: medidaUnidade.UNIDADE,
        preco: 3.5,
        ativo: true,
        criadoEm: addMinutes(7),
      },
      {
        nome: 'Iogurte natural',
        idCategoria: 8,
        descricao: 'Iogurte natural sem açúcar',
        marca: 'Laticínios do Vale',
        alergenos: ['lactose'],
        tipoUnidade: tipoUnidade.VOLUME,
        medidaUnidade: medidaUnidade.POTE,
        preco: 8.75,
        ativo: true,
        criadoEm: addMinutes(8),
      },
      {
        nome: 'Pasta de amendoim',
        idCategoria: 9,
        descricao: 'Pasta cremosa para lanches',
        marca: 'Nuts Good',
        alergenos: ['amendoim'],
        tipoUnidade: tipoUnidade.PESO,
        medidaUnidade: medidaUnidade.POTE,
        preco: 18.4,
        ativo: true,
        criadoEm: addMinutes(9),
      },
      {
        nome: 'Pão integral',
        idCategoria: 10,
        descricao: 'Pão integral fatiado',
        marca: 'Padaria Central',
        alergenos: ['gluten'],
        tipoUnidade: tipoUnidade.UNIDADE,
        medidaUnidade: medidaUnidade.UNIDADE,
        preco: 11.2,
        ativo: true,
        criadoEm: addMinutes(10),
      },
      {
        nome: 'Arroz integral',
        idCategoria: 11,
        descricao: 'Arroz integral para refeições balanceadas',
        marca: 'Grao Verde',
        alergenos: [],
        tipoUnidade: tipoUnidade.PESO,
        medidaUnidade: medidaUnidade.KILO,
        preco: 8.9,
        ativo: true,
        criadoEm: addMinutes(11),
      },
      {
        nome: 'Feijao carioca',
        idCategoria: 12,
        descricao: 'Feijao tradicional para o dia a dia',
        marca: 'Sabor da Terra',
        alergenos: [],
        tipoUnidade: tipoUnidade.PESO,
        medidaUnidade: medidaUnidade.KILO,
        preco: 7.45,
        ativo: true,
        criadoEm: addMinutes(12),
      },
      {
        nome: 'Macarrao integral',
        idCategoria: 13,
        descricao: 'Macarrao integral para pratos rapidos',
        marca: 'Bella Massa',
        alergenos: ['gluten'],
        tipoUnidade: tipoUnidade.PESO,
        medidaUnidade: medidaUnidade.PACOTE,
        preco: 6.8,
        ativo: true,
        criadoEm: addMinutes(13),
      },
      {
        nome: 'Molho de tomate',
        idCategoria: 14,
        descricao: 'Molho pronto para massas e receitas',
        marca: 'Campo Bom',
        alergenos: [],
        tipoUnidade: tipoUnidade.VOLUME,
        medidaUnidade: medidaUnidade.SACHÊ,
        preco: 4.25,
        ativo: true,
        criadoEm: addMinutes(14),
      },
      {
        nome: 'Queijo minas',
        idCategoria: 15,
        descricao: 'Queijo minas fresco para lanches',
        marca: 'Laticinios do Vale',
        alergenos: ['lactose'],
        tipoUnidade: tipoUnidade.PESO,
        medidaUnidade: medidaUnidade.POTE,
        preco: 14.9,
        ativo: true,
        criadoEm: addMinutes(15),
      },
      {
        nome: 'Peito de peru',
        idCategoria: 16,
        descricao: 'Fatiado leve para sanduiches',
        marca: 'Frios Prime',
        alergenos: [],
        tipoUnidade: tipoUnidade.PESO,
        medidaUnidade: medidaUnidade.PACOTE,
        preco: 17.3,
        ativo: true,
        criadoEm: addMinutes(16),
      },
      {
        nome: 'Alface crespa',
        idCategoria: 17,
        descricao: 'Folhas frescas para saladas e lanches',
        marca: 'Horta Viva',
        alergenos: [],
        tipoUnidade: tipoUnidade.UNIDADE,
        medidaUnidade: medidaUnidade.UNIDADE,
        preco: 4.1,
        ativo: true,
        criadoEm: addMinutes(17),
      },
      {
        nome: 'Cenoura',
        idCategoria: 18,
        descricao: 'Cenoura fresca para saladas e refogados',
        marca: 'Horta Viva',
        alergenos: [],
        tipoUnidade: tipoUnidade.PESO,
        medidaUnidade: medidaUnidade.KILO,
        preco: 5.2,
        ativo: true,
        criadoEm: addMinutes(18),
      },
      {
        nome: 'Batata doce',
        idCategoria: 19,
        descricao: 'Batata doce para receitas fitness',
        marca: 'Granja Natural',
        alergenos: [],
        tipoUnidade: tipoUnidade.PESO,
        medidaUnidade: medidaUnidade.KILO,
        preco: 6.95,
        ativo: true,
        criadoEm: addMinutes(19),
      },
      {
        nome: 'Isca de peixe',
        idCategoria: 20,
        descricao: 'Proteina leve para almoços e jantares',
        marca: 'Mar Azul',
        alergenos: ['peixe'],
        tipoUnidade: tipoUnidade.PESO,
        medidaUnidade: medidaUnidade.KILO,
        preco: 24.8,
        ativo: true,
        criadoEm: addMinutes(20),
      },
      {
        nome: 'Cuscuz',
        idCategoria: 21,
        descricao: 'Cuscuz nordestino para cafe da manha',
        marca: 'Sabor do Sertao',
        alergenos: [],
        tipoUnidade: tipoUnidade.PESO,
        medidaUnidade: medidaUnidade.PACOTE,
        preco: 5.6,
        ativo: true,
        criadoEm: addMinutes(21),
      },
      {
        nome: 'Manteiga',
        idCategoria: 22,
        descricao: 'Manteiga cremosa para preparos e paes',
        marca: 'Campo Bom',
        alergenos: ['lactose'],
        tipoUnidade: tipoUnidade.PESO,
        medidaUnidade: medidaUnidade.POTE,
        preco: 9.75,
        ativo: true,
        criadoEm: addMinutes(22),
      },
      {
        nome: 'Suco de laranja',
        idCategoria: 23,
        descricao: 'Suco natural pronto para consumo',
        marca: 'Fruta Pura',
        alergenos: [],
        tipoUnidade: tipoUnidade.VOLUME,
        medidaUnidade: medidaUnidade.LITRO,
        preco: 7.9,
        ativo: true,
        criadoEm: addMinutes(23),
      },
      {
        nome: 'Granola',
        idCategoria: 24,
        descricao: 'Granola crocante para iogurtes e frutas',
        marca: 'Vital Natural',
        alergenos: ['gluten'],
        tipoUnidade: tipoUnidade.PESO,
        medidaUnidade: medidaUnidade.PACOTE,
        preco: 11.4,
        ativo: true,
        criadoEm: addMinutes(24),
      },
      {
        nome: 'Abacate',
        idCategoria: 25,
        descricao: 'Abacate maduro para vitaminas e cremes',
        marca: 'Horta Viva',
        alergenos: [],
        tipoUnidade: tipoUnidade.UNIDADE,
        medidaUnidade: medidaUnidade.UNIDADE,
        preco: 8.3,
        ativo: true,
        criadoEm: addMinutes(25),
      },
      {
        nome: 'Oregano',
        idCategoria: 26,
        descricao: 'Tempero seco para pizzas e massas',
        marca: 'Temperos da Casa',
        alergenos: [],
        tipoUnidade: tipoUnidade.PESO,
        medidaUnidade: medidaUnidade.SACHÊ,
        preco: 3.15,
        ativo: true,
        criadoEm: addMinutes(26),
      },
      {
        nome: 'Cacau em po',
        idCategoria: 27,
        descricao: 'Cacau para bebidas e sobremesas',
        marca: 'Natura Cacau',
        alergenos: [],
        tipoUnidade: tipoUnidade.PESO,
        medidaUnidade: medidaUnidade.POTE,
        preco: 12.6,
        ativo: true,
        criadoEm: addMinutes(27),
      },
      {
        nome: 'Azeite de oliva',
        idCategoria: 28,
        descricao: 'Azeite extra para finalizacao de pratos',
        marca: 'Ouro Verde',
        alergenos: [],
        tipoUnidade: tipoUnidade.VOLUME,
        medidaUnidade: medidaUnidade.FRASCO,
        preco: 19.9,
        ativo: true,
        criadoEm: addMinutes(28),
      },
      {
        nome: 'Hamburguer vegetal',
        idCategoria: 29,
        descricao: 'Opcao vegetal para lanches e pratos',
        marca: 'Veg Life',
        alergenos: ['soja'],
        tipoUnidade: tipoUnidade.PESO,
        medidaUnidade: medidaUnidade.UNIDADE,
        preco: 16.7,
        ativo: true,
        criadoEm: addMinutes(29),
      },
      {
        nome: 'Mel',
        idCategoria: 30,
        descricao: 'Mel puro para doces e vitaminas',
        marca: 'Apiario Real',
        alergenos: [],
        tipoUnidade: tipoUnidade.VOLUME,
        medidaUnidade: medidaUnidade.FRASCO,
        preco: 13.2,
        ativo: true,
        criadoEm: addMinutes(30),
      },
    ],
    { chunk: 10 },
  );

  const clientes = await usuarioRepository.save(
    [
      {
        nome: 'Ana Costa',
        email: 'ana.costa@teste.local',
        senha: 'senha123',
        ativo: true,
        preferencias: ['fit', 'cafe-da-manha'],
        pontos: 0,
        tipoUsuario: TipoUsuario.CLIENTE,
      },
      {
        nome: 'Bruno Lima',
        email: 'bruno.lima@teste.local',
        senha: 'senha123',
        ativo: true,
        preferencias: ['jantar', 'proteina'],
        pontos: 0,
        tipoUsuario: TipoUsuario.CLIENTE,
      },
      {
        nome: 'Carla Souza',
        email: 'carla.souza@teste.local',
        senha: 'senha123',
        ativo: true,
        preferencias: ['lanche', 'rapido'],
        pontos: 0,
        tipoUsuario: TipoUsuario.CLIENTE,
      },
      {
        nome: 'Diego Alves',
        email: 'diego.alves@teste.local',
        senha: 'senha123',
        ativo: true,
        preferencias: ['saudavel'],
        pontos: 0,
        tipoUsuario: TipoUsuario.CLIENTE,
      },
      {
        nome: 'Elaine Rocha',
        email: 'elaine.rocha@teste.local',
        senha: 'senha123',
        ativo: true,
        preferencias: ['sopas', 'low-carb'],
        pontos: 0,
        tipoUsuario: TipoUsuario.CLIENTE,
      },
    ],
    { chunk: 5 },
  );

  await usuarioRepository.save(
    [
      {
        nome: 'Admin 1',
        email: 'admin1@teste.local',
        senha: 'admin123',
        ativo: true,
        tipoUsuario: TipoUsuario.ADMIN,
      },
      {
        nome: 'Admin 2',
        email: 'admin2@teste.local',
        senha: 'admin123',
        ativo: true,
        tipoUsuario: TipoUsuario.ADMIN,
      },
      {
        nome: 'Admin 3',
        email: 'admin3@teste.local',
        senha: 'admin123',
        ativo: true,
        tipoUsuario: TipoUsuario.ADMIN,
      },
      {
        nome: 'Admin 4',
        email: 'admin4@teste.local',
        senha: 'admin123',
        ativo: true,
        tipoUsuario: TipoUsuario.ADMIN,
      },
      {
        nome: 'Admin 5',
        email: 'admin5@teste.local',
        senha: 'admin123',
        ativo: true,
        tipoUsuario: TipoUsuario.ADMIN,
      },
    ],
    { chunk: 5 },
  );

  const receitas = await receitaRepository.save(
    [
      {
        titulo: 'Omelete proteico',
        descricao: 'Omelete simples com ingredientes básicos do café da manhã.',
        pontosRecompensa: 30,
        modoPreparo: 'Bata os ovos, misture os ingredientes e cozinhe em fogo baixo.',
        tempoPreparo: 15,
        porcao: 1,
        categoria: 'Cafe da Manha',
        tags: ['fit', 'proteico'],
        dificuldade: tipoDificuldade.FACIL,
        criadoEm: addMinutes(20),
      },
      {
        titulo: 'Vitamina energética',
        descricao: 'Vitamina cremosa para um lanche rápido.',
        pontosRecompensa: 25,
        modoPreparo: 'Bata todos os ingredientes no liquidificador.',
        tempoPreparo: 10,
        porcao: 2,
        categoria: 'Lanche',
        tags: ['rapido', 'energia'],
        dificuldade: tipoDificuldade.FACIL,
        criadoEm: addMinutes(21),
      },
      {
        titulo: 'Bowl de frango',
        descricao: 'Bowl completo com proteína e carboidrato.',
        pontosRecompensa: 40,
        modoPreparo: 'Monte o bowl com os ingredientes já preparados.',
        tempoPreparo: 20,
        porcao: 2,
        categoria: 'Almoco',
        tags: ['proteina', 'principal'],
        dificuldade: tipoDificuldade.MEDIO,
        criadoEm: addMinutes(22),
      },
      {
        titulo: 'Salada fresca',
        descricao: 'Salada leve com ingredientes frescos.',
        pontosRecompensa: 18,
        modoPreparo: 'Higienize, pique e misture tudo em uma tigela.',
        tempoPreparo: 12,
        porcao: 2,
        categoria: 'Jantar',
        tags: ['leve', 'salada'],
        dificuldade: tipoDificuldade.FACIL,
        criadoEm: addMinutes(23),
      },
      {
        titulo: 'Sanduiche integral',
        descricao: 'Sanduíche prático para qualquer hora do dia.',
        pontosRecompensa: 22,
        modoPreparo: 'Monte o sanduíche com os ingredientes e sirva.',
        tempoPreparo: 8,
        porcao: 1,
        categoria: 'Lanche',
        tags: ['pratico', 'integral'],
        dificuldade: tipoDificuldade.FACIL,
        criadoEm: addMinutes(24),
      },
    ],
    { chunk: 5 },
  );

  await receitaIngredienteRepository.save(
    [
      {
        receita: receitas[0],
        produto: produtos[0],
        unidade: 'unidade',
        opcional: false,
        notas: 'Base principal da receita',
      },
      {
        receita: receitas[0],
        produto: produtos[1],
        unidade: 'unidade',
        opcional: false,
        notas: 'Uso para dar textura',
      },
      {
        receita: receitas[0],
        produto: produtos[2],
        unidade: 'unidade',
        opcional: false,
        notas: 'Complementa o sabor',
      },
      {
        receita: receitas[0],
        produto: produtos[6],
        unidade: 'unidade',
        opcional: true,
        notas: 'Finalização opcional',
      },
      {
        receita: receitas[1],
        produto: produtos[1],
        unidade: 'unidade',
        opcional: false,
        notas: 'Base da vitamina',
      },
      {
        receita: receitas[1],
        produto: produtos[3],
        unidade: 'colher',
        opcional: false,
        notas: 'Adiciona fibras',
      },
      {
        receita: receitas[1],
        produto: produtos[4],
        unidade: 'ml',
        opcional: false,
        notas: 'Liquido principal',
      },
      {
        receita: receitas[1],
        produto: produtos[7],
        unidade: 'unidade',
        opcional: true,
        notas: 'Opcional para incrementar',
      },
      {
        receita: receitas[2],
        produto: produtos[0],
        unidade: 'unidade',
        opcional: false,
        notas: 'Fonte de proteína',
      },
      {
        receita: receitas[2],
        produto: produtos[3],
        unidade: 'colher',
        opcional: false,
        notas: 'Base do bowl',
      },
      {
        receita: receitas[2],
        produto: produtos[5],
        unidade: 'g',
        opcional: false,
        notas: 'Proteína principal',
      },
      {
        receita: receitas[3],
        produto: produtos[2],
        unidade: 'unidade',
        opcional: false,
        notas: 'Frescor da salada',
      },
      {
        receita: receitas[3],
        produto: produtos[6],
        unidade: 'unidade',
        opcional: false,
        notas: 'Aromatiza o prato',
      },
      {
        receita: receitas[3],
        produto: produtos[7],
        unidade: 'pote',
        opcional: false,
        notas: 'Creme opcional na finalização',
      },
      {
        receita: receitas[3],
        produto: produtos[8],
        unidade: 'colher',
        opcional: true,
        notas: 'Extra opcional',
      },
      {
        receita: receitas[4],
        produto: produtos[4],
        unidade: 'ml',
        opcional: false,
        notas: 'Umidade do sanduíche',
      },
      {
        receita: receitas[4],
        produto: produtos[8],
        unidade: 'colher',
        opcional: false,
        notas: 'Pasta principal',
      },
      {
        receita: receitas[4],
        produto: produtos[9],
        unidade: 'fatia',
        opcional: false,
        notas: 'Base do sanduíche',
      },
      {
        receita: receitas[4],
        produto: produtos[1],
        unidade: 'unidade',
        opcional: true,
        notas: 'Acompanhamento opcional',
      },
    ],
    { chunk: 20 },
  );

  const totalClientes = clientes.length;
  console.log(
    `Seed concluida: ${totalClientes} clientes, 5 admins, 30 produtos, 5 receitas e ${receitaIngredienteRepository.metadata.tableName} populada.`,
  );

  await app.close();
}

seed().catch((error) => {
  console.error('Erro ao executar seed:', error);
  process.exitCode = 1;
});
